### ISSUE TITLE
请问如何改制成 Linux 下使用的？

### ISSUE THREAD

**Issue by inkss** [qiuzhiqian/ScreenShotTool#1]
引用了 windows.h 后，怎么解决掉这个引用呢?

**Comment by qiuzhiqian** [comment]
由于使用了windows机制下的一个全局热键的功能，所以导致该软件目前在linux下运行有一些问题，只要把全局热键部分的代码剔除掉基本就可以在linux下正常跑起来了。

**Comment by inkss** [comment]
能不能厚脸皮的问下怎么改？我把备注中标记 windows 时间相关的代码直接删除后，编译运行后没有别的动作了

**Comment by qiuzhiqian** [comment]
我重新对windows平台相关的代码做了宏处理，你在看看有没有效果。如果还不行我再抽空找台linux电脑调调

**Comment by inkss** [comment]
谢谢大神，就是现在程序可以编译通过，托盘上存在程序。只是似乎没有快捷键能够触发截图操作。

文中提到的 QT 的官方 demo ，那个例子我在本机运行了是可以。所以现在是不是快捷键部分不行。是在不行的话，不然我添加一个按钮上去，就用官方的例子延迟截图？

**Comment by inkss** [comment]
![2018-06-16 21-59-24](https://user-images.githubusercontent.com/31947043/41499355-64f8e79e-71b1-11e8-9a91-1606c8c335ce.png)

这个是截图

**Comment by qiuzhiqian** [comment]
其实是我没有做linux快捷键的适配，我抽空加上去吧。^_^

**Comment by qiuzhiqian** [comment]
新版本已经引入qxt库，实现了对win和linux全局热键的支持。
测试环境：
1、win10 1803
2、Linux Arch Plasma5

**Comment by inkss** [comment]
我试了恩可以使用，哈。然后就是那种多次触发截图这个算是一个小bug吧，截图上继续截图？
然后多语言这块，那两个我是没变异出来过。
